version: '3.1'

services:
  database_dev:
    container_name: 'waiterapp_db_dev'
    image: 'mongo:6.0.3'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'mongo'
      MONGO_INITDB_ROOT_PASSWORD: 'docker'
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo-network

volumes:
  mongodb:
  mongoconfig:

networks:
  mongo-network:
    driver: bridge
