version: "3.1"

services:
  queue_dev:
    container_name: "waiterapp_queue_dev"
    image: "redis:alpine3.17"
    restart: unless-stopped
    command: redis-server --save 20 1
    environment:
      REDIS_PASSWORD: "docker"
    ports:
      - 6379:6379
    volumes:
      - queue_dev:/data
    networks:
      - redis-network

volumes:
  queue_dev:
    driver: local

networks:
  redis-network:
    driver: bridge
